AWSTemplateFormatVersion: 2010-09-09
Description: S3 Deployment Layer
Parameters:
  AllowedPrincipal:
    Type: String
    Description: Account principal allowed to deploy this layer
    Default: '*'
  DeploymentBucketName:
    Type: String
  DeploymentKey:
    Type: String

Resources:
  S3DeploymentLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.6
      Description: S3 Deployment Layer
      LayerName: s3-deployment
      LicenseInfo: MIT
      Content:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: !Ref DeploymentKey

  DeploymentPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref S3DeploymentLayer
      Principal: !Ref AllowedPrincipal

Outputs:
  Arn: 
    Value: !Ref S3DeploymentLayer